title:              UJaJuck's Repository
email:              ujajuck@kakao.com
description:        Tech Blog
author:             UJaJuck
baseurl:            ""
url:                "https://ujajcuk.github.io"

# Social Profiles
twitter_username:   ujajuck
github_username:    ujajuck
facebook_username:  ujajuck
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  parse_block_html: true
highlighter:        rouge
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
